R.lm = lm(Sales~Radio, data=Advertising)
summary(R.lm)
plot(Advertising$Sales~Advertising$Radio, col="blue")
points(Advertising$Radio,predict(R.lm), col="orange")
resid(R.lm)
plot(density(resid(R.lm)))
qqnorm(resid(R.lm))
qqline(resid(R.lm))

TVR.lm = lm(Sales~TV+Radio, data=Advertising)
summary(TVR.lm)
resid(TVR.lm)
plot(density(resid(TVR.lm)))
qqnorm(resid(TVR.lm))
qqline(resid(TVR.lm))
